@baseURL = https://localhost:6000/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDAyMjkzMCwiZXhwIjoxNzQwMDI2NTMwLCJjbGFpbXMiOnsibmFtZSI6IlNwb29ydGhpIEcgUyIsImVtYWlsIjoic3Bvb3J0aGlAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwidXNlck5hbWUiOiJzcG9vcnRoaS1ncyJ9fQ.fpfgwTq_TVQKODUcHC9kcwtI77-BCh2uRSJchqzIXqMm7er97COKZSn3z9G5bi9lsK4sl1pqTOKqKY9jFQ-Eircmu32NyO_wjEIwGMgISFLppbB7U-MmBlmtwkK3-9iF1Hcb1dxayxGT8QSZRMeiZUPu19b5BA7_2XK-Mgin8hWZpLqZFVJ1oxZR_-vAry86a8AzZlgWHeP2JSJsbG0D2ARsimttmTWYoztmanax9rDCgKUFkwqdcVNF66B9geAcUnYBYTINE0an58bFlHW1HToHIIycipor5xV0ptJFeVp1T4SDJXLssHfuEr-0EWzDO4ONfeYg_PY_L4TB7mElwQ

### GET all admins
GET {{baseURL}}/admins
Authorization: Bearer {{token}}

### GET all the count ticketWithState
GET {{baseURL}}/admins/guru-pruthvi/ticketWithState
Authorization: Bearer {{token}}

### GET all the count ticketWithCity 
GET {{baseURL}}/admins/guru-pruthvi/ticketWithCity
Authorization: Bearer {{token}}

### GET all the count ticketWithDomain
GET {{baseURL}}/admins/guru-pruthvi/ticketWithDomain
Authorization: Bearer {{token}}

### GET all the count ticketWithLatAndLog
GET {{baseURL}}/admins/guru-pruthvi/ticketWithLatAndLog
Authorization: Bearer {{token}}


### GET an admin by ID
GET {{baseURL}}/admins/admin12345
Authorization: Bearer {{token}}

### GET an admin with INVALID ID
GET {{baseURL}}/admins/INVALID_ID

### POST a new admin
POST {{baseURL}}/admins
Content-Type: application/json

{
    "Admin_ID": "admin12345",
    "email": "guru@example.com",
    "password": "securePass123",
    "username": "guru_pruthvi",
    "phone_Number": "9876543210",
    "name": "Guru Pruthvi",
    "department": "finance"
}

### POST a new admin
POST {{baseURL}}/admins 
Content-Type: application/json

{
    "Admin_ID": "admin67890",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}

### DELETE the admin by ID
DELETE {{baseURL}}/admins/admin12345

### PUT to update the admin details
PUT {{baseURL}}/admins/admin12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "department": "operations"
}
