@baseURL = https://localhost:6000/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTk4ODE0MSwiZXhwIjoxNzM5OTkxNzQxLCJjbGFpbXMiOnsibmFtZSI6IlNwb29ydGhpIEcgUyIsImVtYWlsIjoic3Bvb3J0aGlAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwidXNlck5hbWUiOiJzcG9vcnRoaS1ncyJ9fQ.Hh3gnXwOyO1hWvUWJcMKxXoW43UWb51Jm78feG70CZmKFQiDUSnBboUW_voLqFaRCrvDcl7XjassPHfVaPKiUn86neSWu8nJJFQBiNbc5V_N2cxIE-VDSU-uMQYhIYJ6QEq2_5h7Enkn7_EZQcUJMrN8yEl4dbuyfCdSeTy7_RKT7vxva3RzCabnKd98SRtUMsfkG4v6k-LZGXnPu75e0W8Nu4D_SdYQwRY2VbDy0ffqU55Q0KmOoNzvPET5n6c6AzG5223XaKGYDES0cYshfGaSRn1Bs15_Tt76S-rezAAHDpToRnZ-192xJZwczdP0ipnPXAB5OIo8EthJE4_Rwg

### GET all admins
GET {{baseURL}}/admins
Authorization: Bearer {{token}}

### GET all the count ticketWithState
GET {{baseURL}}/admins/guru-pruthvi/ticketWithState
Authorization: Bearer {{token}}

### GET all the count ticketWithCity 
GET {{baseURL}}/admins/guru-pruthvi/ticketWithCity
Authorization: Bearer {{token}}

### GET all the count ticketWithDomain
GET {{baseURL}}/admins/guru-pruthvi/ticketWithDomain
Authorization: Bearer {{token}}

### GET all the count ticketWithLatAndLog
GET {{baseURL}}/admins/guru-pruthvi/ticketWithLatAndLog
Authorization: Bearer {{token}}


### GET an admin by ID
GET {{baseURL}}/admins/admin12345
Authorization: Bearer {{token}}

### GET an admin with INVALID ID
GET {{baseURL}}/admins/INVALID_ID

### POST a new admin
POST {{baseURL}}/admins
Content-Type: application/json

{
    "Admin_ID": "admin12345",
    "email": "guru@example.com",
    "password": "securePass123",
    "username": "guru_pruthvi",
    "phone_Number": "9876543210",
    "name": "Guru Pruthvi",
    "department": "finance"
}

### POST a new admin
POST {{baseURL}}/admins 
Content-Type: application/json

{
    "Admin_ID": "admin67890",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}

### DELETE the admin by ID
DELETE {{baseURL}}/admins/admin12345

### PUT to update the admin details
PUT {{baseURL}}/admins/admin12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "department": "operations"
}
