@baseURL = https://localhost/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDU4MDEzOCwiZXhwIjoxNzQwNTgzNzM4LCJjbGFpbXMiOnsibmFtZSI6Ikd1cnUgUHJ1dGh2aSIsImVtYWlsIjoiZ3VydXBydXRodmk2MUBnbWFpbC5jb20iLCJyb2xlcyI6WyJjdXN0b21lciJdLCJ1c2VyTmFtZSI6Imd1cnUtcHJ1dGh2aSJ9fQ.Hd9n6i9MJsHpMYT4djJ96sVvIcvvkwAh1gxQQn381XbvWFTc0OZBi_wTnuylz3qt3IC9kjjf_lONfVgqA9FCuDTzpCsEqj0DtFZrRZ4liGeQ2TIutjs8kKL6d5QaaIuOJWmK3btn8x4h-x9aP5QrQc13FJp7tr6oAzjM8DguI4IGBBou6HqTYioZ76nsurl31VRbznvqZJc9B_sddnXfuZ7bUcHGdMlHsS8iXoHyYDZyJ8c1B43Nsz5snF6ML7O1M74DcKm_6P_xAEd96zejWpJ-CP_-TOR-NDWWUeSNcnV7zY_hsPkRvu8R2G6dyhuAtf8OlJZ1WflkXin7EdLvzg

### GET all customers
GET {{baseURL}}/customers
Authorization: BEARER {{token}}

### GET a customer by ID
GET {{baseURL}}/customers/jyothish-m-j
Authorization: BEARER {{token}}

### GET a payment by particular customer
GET {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}

### POST a payment by particular customer
POST {{baseURL}}/customers/guru-pruthvi/payments
Content-Type: application/json

{
    "amount": 50000,
    "department": "finance"
}

### GET a ticket raised by a customer
GET {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}

### POST a ticket raised by a customer
POST  {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "ticketDescription": "There is a Glich in the Dashboard.",
    "department": "Product-and-Platform-Engineering" 
}


### GET a customer with INVALID ID
GET {{baseURL}}/customers/INVALID_ID

### POST a new customer
POST {{baseURL}}/customers
Content-Type: application/json

{
  "name": "Jyothish M J",
  "phone_Number": "9632888266",
  "username": "jyothish m j",
  "password": "securePass123",
  "email": "jyo@example.com",
  "roles": ["customer"],
  "address": "123 Main Street",
  "pinCode": 571105
}


### POST a new Different Customer
POST {{baseURL}}/customers
Content-Type: application/json

{
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru"
}


### Delete the customer by id
DELETE {{baseURL}}/customers/guru-pruthvi


### PUT to update the customer Details
PUT {{baseURL}}/customers/jyothish-m-j
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "email": "gurupruthvi61@gmail.com"
}

### POST a new Raise Ticket by particular ticket

POST {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "ticketType": "Amount",
    "ticketDescription": "Unable to See my wallet",
    "department": "finance"
}

### POST a new Payment

POST {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "amount": 500,
    "paymentType": "GPay",
    "department": "jio"
}
