@baseURL = https://localhost/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDIwMzcxMiwiZXhwIjoxNzQwMjA3MzEyLCJjbGFpbXMiOnsibmFtZSI6IlByYW5hdGhpIiwiZW1haWwiOiJwcmFuYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sInVzZXJOYW1lIjoicHJhbmEifX0.aPTIWs_Grc6WLj1D8F9W0zl0Ohbz8AvjZn4IOm0Kqadx01udbNE9OnCqHDcaN-afyZy7K8wj8hNW35inOQ6opORSPUi65Ffe5kkYFM6gkrEwxHCSR50dQa6kOb9fJkUgwZ7q5AMPzoK4v4SxIt5Uh1evgnln3RSeY07wx5JANWS4MiZBNiqk1AVkwEL3wRB22O5Hgzl7waR305NH9dSGthbv3NS8Vd4URD_N2rHrrWVIn_eLKw-Gh_g8bmWUCYByhYwYdKCIUBNoKZ9j_5Pi2X19kWLbSjvG6I3qYABrVfd9vcPc1-BAZO1Z240w4qRE7jn2EFdGw4HmJeMguLYn3w

### GET all customers
GET {{baseURL}}/customers
Authorization: BEARER {{token}}

### GET a customer by ID
GET {{baseURL}}/customers/jyothish-m-j
Authorization: BEARER {{token}}

### GET a payment by particular customer
GET {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}

### POST a payment by particular customer
POST {{baseURL}}/customers/guru-pruthvi/payments
Content-Type: application/json

{
    "amount": 50000,
    "department": "finance"
}

### GET a ticket raised by a customer
GET {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}

### POST a ticket raised by a customer
POST  {{baseURL}}/customers/jyothish-m-j/tickets
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "ticketType": "Technical Issue",
    "ticketDescription": "Unable to pay to buy the discription.",
    "ticketStatus": "OPEN",
    "department": "finance"
}


### GET a customer with INVALID ID
GET {{baseURL}}/customers/INVALID_ID

### POST a new customer
POST {{baseURL}}/customers
Content-Type: application/json

{
  "name": "Jyothish M J",
  "phone_Number": "9632888266",
  "username": "jyothish m j",
  "password": "securePass123",
  "email": "jyo@example.com",
  "roles": ["customer"],
  "address": "123 Main Street",
  "pinCode": 571105
}


### POST a new Different Customer
POST {{baseURL}}/customers
Content-Type: application/json

{
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru"
}


### Delete the customer by id
DELETE {{baseURL}}/customers/guru-pruthvi


### PUT to update the customer Details
PUT {{baseURL}}/customers/jyothish-m-j
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "email": "gurupruthvi61@gmail.com"
}

### POST a new Raise Ticket by particular ticket

POST {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "ticketType": "Amount",
    "ticketDescription": "Unable to See my wallet",
    "department": "finance"
}

### POST a new Payment

POST {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "amount": 500,
    "paymentType": "GPay",
    "department": "jio"
}
