@baseURL = https://localhost/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTkyNzQzNCwiZXhwIjoxNzM5OTMxMDM0LCJjbGFpbXMiOnsibmFtZSI6IlByYW5hdGhpIiwiZW1haWwiOiJwcmFuYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sInVzZXJOYW1lIjoicHJhbmEifX0.FGbv923NMe8CrrlhTlDrJoaDqH6LAoOgEXrzWU5W8DAeY5N8celHRRlDLqySc0Uta3-Tkbn2e2tOdL01vez9wHEcCbca5eIpdS-K782aYLTsUmKDRDHSXjWvuKNf3UE5FROlnR8KLDWPxbiLJmU2pAS8x3f9u4jYgrnD2ejjpoRFxSP2QG3HVgzgEkx6a7zkeybwxhTQ8H2ky5LoDVMzhx5w8Pb0aSg5Ldj__KVrkCA_fOWUL65oJleSudcGHJDCy2lSfceVzHlF-Ulm63bLiSFZrfOgwX07qfCaoM_Ui38pC8XeU2UB1ARlnWzkEMpmoFMwnM35BAuUq-tQY2qptQ

### GET all customers
GET {{baseURL}}/customers
Authorization: BEARER {{token}}

### GET a customer by ID
GET {{baseURL}}/customers/guru-pruthvi

### GET a payment by particular customer
GET {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}

### POST a payment by particular customer
POST {{baseURL}}/customers/guru-pruthvi/payments
Content-Type: application/json

{
    "amount": 50000,
    "department": "finance"
}

### GET a ticket raised by a customer
GET {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}

### POST a ticket raised by a customer
POST  {{baseURL}}/customers/guru-pruthvi/tickets
Content-Type: application/json

{
    "ticketType": "Technical Issue",
    "ticketDescription": "Unable to pay to buy the discription.",
    "ticketStatus": "Open",
    "department": "finance"
}


### GET a customer with INVALID ID
GET {{baseURL}}/customers/INVALID_ID

### POST a new customer
POST {{baseURL}}/customers
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass123",
    "username": "guru pruthvi",
    "phone_Number": "9876543210",
    "name": "Guru Pruthvi"
}

### POST a new Different Customer
POST {{baseURL}}/customers
Content-Type: application/json

{
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru"
}


### Delete the customer by id
DELETE {{baseURL}}/customers/guru-pruthvi


### PUT to update the customer Details
PUT {{baseURL}}/customers/guru-pruthvi
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru pruthvi"
}

### POST a new Raise Ticket by particular ticket

POST {{baseURL}}/customers/guru-pruthvi/tickets
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "ticketType": "Amount",
    "ticketDescription": "Unable to See my wallet",
    "department": "finance"
}

### POST a new Payment

POST {{baseURL}}/customers/guru-pruthvi/payments
Authorization: BEARER {{token}}
Content-Type: application/json

{
    "amount": 500,
    "paymentType": "GPay",
    "department": "jio"
}
