@baseURL = https://localhost:8000/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTU5NzE2MSwiZXhwIjoxNzM5NjAwNzYxLCJjbGFpbXMiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsiZW1wbG95ZWUiXX19.cPo_CE1M4WXDY-i-IxPXpVIoJsop7i2N4TzuOeiDcIVegm6ZlEhvi5e936gWQWhCizYMwXcbr9Hq10_geK5dI6gHC9Y3lJxw8lF-XCeErz3XvatuSAal1I-DDojQvTRXuZ5UWwsKROCWOYNpPwVk-E6YpRHtbg2ZZ57k7z6S0n1NDJkgLcXxJpycIwK_bAy2tyVw4WnbvwduFUH9-ipzCrw2IIz8HWf0Wbd2HCt0GmotD8kwt7LsiPDWNs_hhU6xLqygTPNmRpnDZJLzO5b3Omal48IAypHDKT7G1ZM9xfQxkv-CDV6mMNnLI5UzTywUGI4y224PY4aTiMzaQ6cx3w

### GET all employees
GET {{baseURL}}/employees
Authorization: BEREAR {{token}}


### GET an employee by ID
GET {{baseURL}}/employees/john-doe

### GET an employee by ID with tickets
GET {{baseURL}}/employees/john-doe/tickets

### GET an employee with INVALID ID
GET {{baseURL}}/employees/INVALID_ID

### POST a new employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "managerId": "MGR001",
    "designation": "Software Engineer",
    "department": "IT",
    "gender": "MALE",
    "dateOfBirth": "1990-05-15",
    "dateOfJoining": "2020-03-01",
    "salary": 75000,
    "email": "john.doe@example.com",
    "phoneNo": "1234567890",
    "password": "securePassword123"
}




### POST a new Different Employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "Jane Smith",
    "managerId": "MGR002",
    "designation": "HR Manager",
    "department": "Human Resources",
    "gender": "FEMALE",
    "dateOfBirth": "1985-10-25",
    "dateOfJoining": "2018-07-10",
    "salary": 85000,
    "email": "jane.smith@example.com",
    "phoneNo": "0987654321",
    "password": "strongPassword456"
  }


### Delete the employee by ID
DELETE {{baseURL}}/employees/john-doe

### PUT to update the employee Details
PUT {{baseURL}}/employees/EMP001
Content-Type: application/json

{
    "EMPLOYEE_TAKEHOME": 60000
}

### Update the ticket status
PUT {{baseURL}}/employees/john-doe/tickets/TICKET456
Content-Type: application/json

{
    "ticketStatus": "CLOSED"
}