@baseURL = https://localhost:8000/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDY0MDY1MywiZXhwIjoxNzQwNjQ0MjUzLCJjbGFpbXMiOnsibmFtZSI6IlJvaGFuIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsiZW1wbG95ZWUiXSwidXNlck5hbWUiOiJqb2huLWRvZSJ9fQ.aZtiDdxgeOEFtUBWCRCrl8AmfWcXGyTT8luMCRHUDjSw9x0rXOxIsuG-cFD5ZS0CRWPR7aoM0es_6AhLQNY6eX26bEU14AzVLQOowOTi8IJrZrslnUIRi4s5O5PYn0Q3qVNg2S44tNl3Z_4cF_6MdZ2HdGQ1PNKSa3dj9zfyR2eYN9VfA8GYWWY5TQcuAMg_e7HIl2Jlmn_LDNgltPI2EfiyWDZDCuJ_o1FTOTESLSKR3colgCczn7uV64bt70kOeXWzi3Ro1GXvymQaRaTn-hyJympQ74cAzqAFJBn4wAQkBoSqXfn0bcfCHvONSsGbBE29DlpQ3sHPLfkmNZfYhg

### GET all employees
GET {{baseURL}}/employees
Authorization: BEREAR {{token}}

### GET all collegues of employees
GET {{baseURL}}/employees/john-doe/collegue
Authorization: BEARER {{token}}



### GET an employee by ID
GET {{baseURL}}/employees/nirmala
Authorization: BEARER {{token}}

### GET an employee by ID with tickets
GET {{baseURL}}/employees/guru-pruthvi-j-m/tickets
Authorization: BEARER {{token}}

### GET an employee stats
GET {{baseURL}}/employees/guru-pruthvi-j-m/stats
Authorization: BEARER {{token}}

### GET an employee with INVALID ID
GET {{baseURL}}/employees/INVALID_ID

### POST a new employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "managerId": "MGR001",
    "designation": "Software Engineer",
    "department": "IT",
    "gender": "MALE",
    "dateOfBirth": "1990-05-15",
    "dateOfJoining": "2020-03-01",
    "salary": 75000,
    "email": "john.doe@example.com",
    "phoneNo": "1234567890",
    "password": "securePassword123"
}




### POST a new Different Employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "Jane Smith",
    "managerId": "MGR002",
    "designation": "HR Manager",
    "department": "Human Resources",
    "gender": "FEMALE",
    "dateOfBirth": "1985-10-25",
    "dateOfJoining": "2018-07-10",
    "salary": 85000,
    "email": "jane.smith@example.com",
    "phoneNo": "0987654321",
    "password": "strongPassword456"
  }


### Delete the employee by ID
DELETE {{baseURL}}/employees/john-doe

### PUT to update the employee Details
PUT {{baseURL}}/employees/EMP001
Content-Type: application/json

{
    "EMPLOYEE_TAKEHOME": 60000
}

### Update the ticket status
PUT {{baseURL}}/employees/nirmala/tickets/jyothish-m-j-1740198888432
Authorization: BEREAR {{token}}
Content-Type: application/json

{
    "ticketStatus": "PENDING"
}