@baseURL = https://localhost:8000/api
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTg1MjUwOCwiZXhwIjoxNzM5ODU2MTA4LCJjbGFpbXMiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsiZW1wbG95ZWUiXSwidXNlck5hbWUiOiJqb2huLWRvZSJ9fQ.B-wo-ymFJ_n4uxQt8IOn_tn_EUegVlwaLeBsDj4knpKNhYJ_z4818SJwNzJxkonU4QVncrca1SXI6MditlmegMBLHLT4vladmUaVExODnKegGB0b2sluqMx8i0pm9S8OZT-UWQprss3KbVz8dNmjGNp6d2Y47rWJ77EE9S14o4cDg2kA5ZbtKvpKuVCwLTcpBTqfpFGwDg04T-_P_LH16qgNrdgTxp5Sy7BgRN54bhzRzpVL3SCWwrqmfDE1VGlRHClSYryMG-JL2M9C9GhokPS-6mhuXc1WfAfd3DQ-B2xSVZJhDnAE-IS32m2B5KxHIP8kpsF0mui1sCoLQmNgNg

### GET all employees
GET {{baseURL}}/employees
Authorization: BEREAR {{token}}

### GET all collegues of employees
GET {{baseURL}}/employees/john-doe/collegue
Authorization: BEARER {{token}}



### GET an employee by ID
GET {{baseURL}}/employees/john-doe

### GET an employee by ID with tickets
GET {{baseURL}}/employees/john-doe/tickets

### GET an employee with INVALID ID
GET {{baseURL}}/employees/INVALID_ID

### POST a new employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "managerId": "MGR001",
    "designation": "Software Engineer",
    "department": "IT",
    "gender": "MALE",
    "dateOfBirth": "1990-05-15",
    "dateOfJoining": "2020-03-01",
    "salary": 75000,
    "email": "john.doe@example.com",
    "phoneNo": "1234567890",
    "password": "securePassword123"
}




### POST a new Different Employee
POST {{baseURL}}/employees
Content-Type: application/json

{
    "name": "Jane Smith",
    "managerId": "MGR002",
    "designation": "HR Manager",
    "department": "Human Resources",
    "gender": "FEMALE",
    "dateOfBirth": "1985-10-25",
    "dateOfJoining": "2018-07-10",
    "salary": 85000,
    "email": "jane.smith@example.com",
    "phoneNo": "0987654321",
    "password": "strongPassword456"
  }


### Delete the employee by ID
DELETE {{baseURL}}/employees/john-doe

### PUT to update the employee Details
PUT {{baseURL}}/employees/EMP001
Content-Type: application/json

{
    "EMPLOYEE_TAKEHOME": 60000
}

### Update the ticket status
PUT {{baseURL}}/employees/john-doe/tickets/TICKET456
Content-Type: application/json

{
    "ticketStatus": "CLOSED"
}