@baseURL = https://localhost:5000/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTg1NDkzMywiZXhwIjoxNzM5ODU4NTMzLCJjbGFpbXMiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsibWFuYWdlciJdfX0.OjePDBrc7dgi1tlntCw7zXrYphVOXWS8XDDaNaEaMKnW1_rDNYWn0dVmNyfmz8dtj-o7ZYJwQixVqIu9xWAjQ7GaIzn9wQ1TfawMvsXZ6LXqxZxwWMkJ8lHRRFl4ZP1ilE-G6XK5nh_9GKksWK-4gNeYWIzYajva82YPoe51-o1BrZl6MpNyL1xI8hfzT5KSANhDwuElAsPgbnMw2KcYVxkeT9M0h8USCAd7zcUlFwNcM65BoXSvom1b74D90XKYr0YbL9apxMT7gnSNNwYtYw3PyX83hZDXgIEn6mOKK_YU8E6qtJ9XJ1u9SUuu3YBYNsNAAWziUKIFqzWkWd3ytQ


###GET all managers
GET {{baseURL}}/managers

### GET a manager by ID
GET {{baseURL}}/managers/mgr12345

###GET a manager with INVALID ID
GET {{baseURL}}/managers/INVALID_ID

### GET Specified ManagerId ticketStatus
GET {{baseURL}}/managers/johndoe/ticketStatus
Authorization: BEARER {{token}}

### Get Specified TicketStatus of specified Manager
GET {{baseURL}}/managers/guru_pruthvi/ticketStatus/closed

### Get Specified TicketStatus of specified Manager with specified ticketId
GET {{baseURL}}/managers/guru_pruthvi/ticketStatus/pending/TICKET567

### Get the specified Manager ticket count of their collegues

GET {{baseURL}}/managers/guru_pruthvi/collegue/ticketCount


### GET all Employee under manager
GET {{baseURL}}/managers/guru_pruthvi/collegue

### GET specific Employee under manager
GET {{baseURL}}/managers/guru_pruthvi/collegue/mahesh-gupta

### POST a new manager
POST {{baseURL}}/managers
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "securePass123",
    "username": "guru prasad",
    "phone_Number": "9886828769",
    "name": "Guru Prasad",
    "department": "operation"
}

### POST a new manager
POST {{baseURL}}/managers 
Content-Type: application/json

{
    "Manager_ID": "manager-102",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}


###Delete the manager by id
DELETE {{baseURL}}/managers/mgr12345

###PUT to update the manager Details
PUT {{baseURL}}/managers/mgr12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "domain": "operations"
}
