@baseURL = https://localhost:5000/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTczOTkzOTQ2NCwiZXhwIjoxNzM5OTQzMDY0LCJjbGFpbXMiOnsibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwicm9sZXMiOlsibWFuYWdlciJdLCJ1c2VyTmFtZSI6ImpvaG5kb2UifX0.FW4mI6EwjKI6yxYPPNxeJCyGXgCtek6m53Ti2N4s3odHzMzl0K799d4kpgIXUB4tVLArUBXfAq1NwRErAyPLsDBG9WD8s_dgQ6iymUVwFb1Qohb25HrQ82hh9SkfNMFaXGS4SPaIScWRHToiGcfbykOinXolOOumcPzmmIF9o8dcX50ZExO0QRj93zjweP3QEITylt8Wh3qb7CY5F2xhQfhuu9WwXLtJ01MhWm8dT_r2ZR0-2E-DT1mJ4dCQHZwk66L67ROWnN8iH_eSgwGyx41g_B6cht_a57fzZvpXyOqAOnXSCkLFPmQveG3JY-H1vpHt1lyELb8JxOeflg210Q

###GET all managers
GET {{baseURL}}/managers

### GET a manager by ID
GET {{baseURL}}/managers/mgr12345

###GET a manager with INVALID ID
GET {{baseURL}}/managers/INVALID_ID

### GET Specified ManagerId ticketStatus
GET {{baseURL}}/managers/johndoe/ticketStatus
Authorization: BEARER {{token}}

### GET Specified ManagerId stats

GET {{baseURL}}/managers/johndoe/stats
Authorization: BEARER {{token}}



### Get Specified TicketStatus of specified Manager
GET {{baseURL}}/managers/johndoe/ticketStatus/closed
Authorization: BEARER {{token}}

### Get Specified TicketStatus of specified Manager with specified ticketId
GET {{baseURL}}/managers/guru_pruthvi/ticketStatus/pending/TICKET567

### Get the specified Manager ticket count of their collegues

GET {{baseURL}}/managers/guru_pruthvi/collegue/ticketCount


### GET all Employee under manager
GET {{baseURL}}/managers/johndoe/collegue
Authorization: BEARER {{token}}

### GET specific Employee under manager
GET {{baseURL}}/managers/guru_pruthvi/collegue/mahesh-gupta

### POST a new manager
POST {{baseURL}}/managers
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "securePass123",
    "username": "guru prasad",
    "phone_Number": "9886828769",
    "name": "Guru Prasad",
    "department": "operation"
}

### POST a new manager
POST {{baseURL}}/managers 
Content-Type: application/json

{
    "Manager_ID": "manager-102",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}


###Delete the manager by id
DELETE {{baseURL}}/managers/mgr12345

###PUT to update the manager Details
PUT {{baseURL}}/managers/mgr12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "domain": "operations"
}
