@baseURL = https://localhost:5000/api

@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJVc2VyQXV0aGVudGljYXRvciIsImlhdCI6MTc0MDc5NDk5NywiZXhwIjoxNzQwNzk4NTk3LCJjbGFpbXMiOnsibmFtZSI6Ik1haGVzaCBHdXB0YSIsImVtYWlsIjoibWFoZXNoZ3VwdGE1ODEyQGdtYWlsLmNvbSIsInJvbGVzIjpbIm1hbmFnZXIiXSwidXNlck5hbWUiOiJtYWhlc2gtZ3VwdGEifX0.RyDmz653iuhEr4r9hpd8N9cUzm7s7LHpswxIGNx4DnXYQJvNPwnU2qp8-kIW5rGUvGWYwDyQsqZf2mUn8y-mzGeIxEcOw7gEDlDMLDu6TLxeZcJ2QIkfVeJIlXJFXjFVxQSqsUBUIMThtKVkM3w9vCO084tZr-XJOkONrA7snleSO4QJdMSLepEFZuMt-I4yK2K6jZtxBWx1qqbNiblOHZ6O3JRApOn_3ix5wuE42y5JOG8CzLpGasCU1_LVEikV_SXhk2Bg0mt-p19_YD8k_bxSCaZRR5xd0qXMdGHNr0CRVmFo1_ZkoogqbWBm3Td4uGGTlinK9zSX6npRCz7Y0A

###GET all managers
GET {{baseURL}}/managers
Authorization: BEARER {{token}}

### GET a manager by ID
GET {{baseURL}}/managers/mgr12345

###GET a manager with INVALID ID
GET {{baseURL}}/managers/INVALID_ID

### GET Specified ManagerId ticketStatus
GET {{baseURL}}/managers/johndoe/ticketStatus
Authorization: BEARER {{token}}

### GET Specified ManagerId stats

GET {{baseURL}}/managers/mahesh-gupta/stats
Authorization: BEARER {{token}}



### Get Specified TicketStatus of specified Manager
GET {{baseURL}}/managers/johndoe/ticketStatus/open
Authorization: BEARER {{token}}

### Get Specified TicketStatus of specified Manager with specified ticketId
GET {{baseURL}}/managers/guru_pruthvi/ticketStatus/pending/TICKET567

### Get the specified Manager ticket count of their collegues

GET {{baseURL}}/managers/mahesh-gupta/collegue/ticketCount
Authorization: BEARER {{token}}


### GET all Employee under manager
GET {{baseURL}}/managers/mahesh-gupta/collegue
Authorization: BEARER {{token}}

### GET specific Employee under manager
GET {{baseURL}}/managers/guru_pruthvi/collegue/nirmala
Authorization: BEARER {{token}}

### POST a new manager
POST {{baseURL}}/managers
Content-Type: application/json

{
    "email": "guru@gmail.com",
    "password": "securePass123",
    "username": "guru prasad",
    "phone_Number": "9886828769",
    "name": "Guru Prasad",
    "department": "operation"
}

### POST a new manager
POST {{baseURL}}/managers 
Content-Type: application/json

{
    "Manager_ID": "manager-102",
    "email": "pruthvi@example.com",
    "password": "securePass456",
    "username": "pruthvi-guru",
    "phone_Number": "9999999999",
    "name": "Pruthvi Guru",
    "department": "sales"
}


###Delete the manager by id
DELETE {{baseURL}}/managers/mgr12345

###PUT to update the manager Details
PUT {{baseURL}}/managers/mgr12345 
Content-Type: application/json

{
    "email": "guru@example.com",
    "password": "securePass",
    "username": "guru_pruthvi",
    "domain": "operations"
}
